// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.1
// source: proto/payments/payments.proto

package paymentspb

import (
	authpb "github.com/cutters-digital/gateway-protobuf/golang/authpb"
	moneypb "github.com/cutters-digital/gateway-protobuf/golang/moneypb"
	utilspb "github.com/cutters-digital/gateway-protobuf/golang/utilspb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PaymentStatus contains all the possible statuses a payment can be in.
type PaymentStatus int32

const (
	PaymentStatus_PAYMENT_STATUS_INVALID        PaymentStatus = 0
	PaymentStatus_PAYMENT_STATUS_UNKNOWN        PaymentStatus = 1
	PaymentStatus_PAYMENT_STATUS_SUCCESS        PaymentStatus = 2
	PaymentStatus_PAYMENT_STATUS_ERROR          PaymentStatus = 3
	PaymentStatus_PAYMENT_STATUS_REQUIRE_ACTION PaymentStatus = 4
)

// Enum value maps for PaymentStatus.
var (
	PaymentStatus_name = map[int32]string{
		0: "PAYMENT_STATUS_INVALID",
		1: "PAYMENT_STATUS_UNKNOWN",
		2: "PAYMENT_STATUS_SUCCESS",
		3: "PAYMENT_STATUS_ERROR",
		4: "PAYMENT_STATUS_REQUIRE_ACTION",
	}
	PaymentStatus_value = map[string]int32{
		"PAYMENT_STATUS_INVALID":        0,
		"PAYMENT_STATUS_UNKNOWN":        1,
		"PAYMENT_STATUS_SUCCESS":        2,
		"PAYMENT_STATUS_ERROR":          3,
		"PAYMENT_STATUS_REQUIRE_ACTION": 4,
	}
)

func (x PaymentStatus) Enum() *PaymentStatus {
	p := new(PaymentStatus)
	*p = x
	return p
}

func (x PaymentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_payments_payments_proto_enumTypes[0].Descriptor()
}

func (PaymentStatus) Type() protoreflect.EnumType {
	return &file_proto_payments_payments_proto_enumTypes[0]
}

func (x PaymentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentStatus.Descriptor instead.
func (PaymentStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_payments_payments_proto_rawDescGZIP(), []int{0}
}

// CardStatus contains all the possible statuses a card can be in.
type CardStatus int32

const (
	CardStatus_CARD_STATUS_INVALID        CardStatus = 0
	CardStatus_CARD_STATUS_UNKNOWN        CardStatus = 1
	CardStatus_CARD_STATUS_SUCCESS        CardStatus = 2
	CardStatus_CARD_STATUS_ERROR          CardStatus = 3
	CardStatus_CARD_STATUS_REQUIRE_ACTION CardStatus = 4
)

// Enum value maps for CardStatus.
var (
	CardStatus_name = map[int32]string{
		0: "CARD_STATUS_INVALID",
		1: "CARD_STATUS_UNKNOWN",
		2: "CARD_STATUS_SUCCESS",
		3: "CARD_STATUS_ERROR",
		4: "CARD_STATUS_REQUIRE_ACTION",
	}
	CardStatus_value = map[string]int32{
		"CARD_STATUS_INVALID":        0,
		"CARD_STATUS_UNKNOWN":        1,
		"CARD_STATUS_SUCCESS":        2,
		"CARD_STATUS_ERROR":          3,
		"CARD_STATUS_REQUIRE_ACTION": 4,
	}
)

func (x CardStatus) Enum() *CardStatus {
	p := new(CardStatus)
	*p = x
	return p
}

func (x CardStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CardStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_payments_payments_proto_enumTypes[1].Descriptor()
}

func (CardStatus) Type() protoreflect.EnumType {
	return &file_proto_payments_payments_proto_enumTypes[1]
}

func (x CardStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CardStatus.Descriptor instead.
func (CardStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_payments_payments_proto_rawDescGZIP(), []int{1}
}

// PaymentMethod represents how customer paid for a service/product.
type PaymentMethod int32

const (
	PaymentMethod_PAYMENT_METHOD_INVALID PaymentMethod = 0
	PaymentMethod_PAYMENT_METHOD_UNKNOWN PaymentMethod = 1
	PaymentMethod_PAYMENT_METHOD_VOUCHER PaymentMethod = 2
	PaymentMethod_PAYMENT_METHOD_STRIPE  PaymentMethod = 3
	PaymentMethod_PAYMENT_METHOD_VIPPS   PaymentMethod = 4
	PaymentMethod_PAYMENT_METHOD_WALLMOB PaymentMethod = 5
)

// Enum value maps for PaymentMethod.
var (
	PaymentMethod_name = map[int32]string{
		0: "PAYMENT_METHOD_INVALID",
		1: "PAYMENT_METHOD_UNKNOWN",
		2: "PAYMENT_METHOD_VOUCHER",
		3: "PAYMENT_METHOD_STRIPE",
		4: "PAYMENT_METHOD_VIPPS",
		5: "PAYMENT_METHOD_WALLMOB",
	}
	PaymentMethod_value = map[string]int32{
		"PAYMENT_METHOD_INVALID": 0,
		"PAYMENT_METHOD_UNKNOWN": 1,
		"PAYMENT_METHOD_VOUCHER": 2,
		"PAYMENT_METHOD_STRIPE":  3,
		"PAYMENT_METHOD_VIPPS":   4,
		"PAYMENT_METHOD_WALLMOB": 5,
	}
)

func (x PaymentMethod) Enum() *PaymentMethod {
	p := new(PaymentMethod)
	*p = x
	return p
}

func (x PaymentMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_payments_payments_proto_enumTypes[2].Descriptor()
}

func (PaymentMethod) Type() protoreflect.EnumType {
	return &file_proto_payments_payments_proto_enumTypes[2]
}

func (x PaymentMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentMethod.Descriptor instead.
func (PaymentMethod) EnumDescriptor() ([]byte, []int) {
	return file_proto_payments_payments_proto_rawDescGZIP(), []int{2}
}

// PaymentRequest contains information about how a payment should be done.
type PaymentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Provider:
	//
	//	*PaymentRequest_Empty
	//	*PaymentRequest_Stripe
	//	*PaymentRequest_Vipps
	Provider isPaymentRequest_Provider `protobuf_oneof:"provider"`
	Voucher  *VoucherRequest           `protobuf:"bytes,3,opt,name=voucher,proto3" json:"voucher,omitempty"`
	Vouchers []*VoucherRequest         `protobuf:"bytes,6,rep,name=vouchers,proto3" json:"vouchers,omitempty"`
	Coupons  []*CouponCode             `protobuf:"bytes,7,rep,name=coupons,proto3" json:"coupons,omitempty"`
	// The expected price for the payment, after discounts/vouchers. The server will not go through with payment if the expected price is different than this amount.
	ExpectedPrice *moneypb.Price `protobuf:"bytes,4,opt,name=expected_price,json=expectedPrice,proto3" json:"expected_price,omitempty"`
}

func (x *PaymentRequest) Reset() {
	*x = PaymentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_payments_payments_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentRequest) ProtoMessage() {}

func (x *PaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payments_payments_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentRequest.ProtoReflect.Descriptor instead.
func (*PaymentRequest) Descriptor() ([]byte, []int) {
	return file_proto_payments_payments_proto_rawDescGZIP(), []int{0}
}

func (m *PaymentRequest) GetProvider() isPaymentRequest_Provider {
	if m != nil {
		return m.Provider
	}
	return nil
}

func (x *PaymentRequest) GetEmpty() *utilspb.Empty {
	if x, ok := x.GetProvider().(*PaymentRequest_Empty); ok {
		return x.Empty
	}
	return nil
}

func (x *PaymentRequest) GetStripe() *StripePaymentRequest {
	if x, ok := x.GetProvider().(*PaymentRequest_Stripe); ok {
		return x.Stripe
	}
	return nil
}

func (x *PaymentRequest) GetVipps() *VippsPaymentRequest {
	if x, ok := x.GetProvider().(*PaymentRequest_Vipps); ok {
		return x.Vipps
	}
	return nil
}

func (x *PaymentRequest) GetVoucher() *VoucherRequest {
	if x != nil {
		return x.Voucher
	}
	return nil
}

func (x *PaymentRequest) GetVouchers() []*VoucherRequest {
	if x != nil {
		return x.Vouchers
	}
	return nil
}

func (x *PaymentRequest) GetCoupons() []*CouponCode {
	if x != nil {
		return x.Coupons
	}
	return nil
}

func (x *PaymentRequest) GetExpectedPrice() *moneypb.Price {
	if x != nil {
		return x.ExpectedPrice
	}
	return nil
}

type isPaymentRequest_Provider interface {
	isPaymentRequest_Provider()
}

type PaymentRequest_Empty struct {
	Empty *utilspb.Empty `protobuf:"bytes,1,opt,name=empty,proto3,oneof"`
}

type PaymentRequest_Stripe struct {
	Stripe *StripePaymentRequest `protobuf:"bytes,2,opt,name=stripe,proto3,oneof"`
}

type PaymentRequest_Vipps struct {
	Vipps *VippsPaymentRequest `protobuf:"bytes,5,opt,name=vipps,proto3,oneof"`
}

func (*PaymentRequest_Empty) isPaymentRequest_Provider() {}

func (*PaymentRequest_Stripe) isPaymentRequest_Provider() {}

func (*PaymentRequest_Vipps) isPaymentRequest_Provider() {}

// CouponCode holds information needed by both requests and responses for working with cutters coupons.
type CouponCode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Valid       bool   `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *CouponCode) Reset() {
	*x = CouponCode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_payments_payments_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CouponCode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CouponCode) ProtoMessage() {}

func (x *CouponCode) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payments_payments_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CouponCode.ProtoReflect.Descriptor instead.
func (*CouponCode) Descriptor() ([]byte, []int) {
	return file_proto_payments_payments_proto_rawDescGZIP(), []int{1}
}

func (x *CouponCode) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CouponCode) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *CouponCode) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// VoucherCode holds information for the app regarding the voucher information in the request.
type VoucherCode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Valid bool   `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
}

func (x *VoucherCode) Reset() {
	*x = VoucherCode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_payments_payments_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VoucherCode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoucherCode) ProtoMessage() {}

func (x *VoucherCode) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payments_payments_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoucherCode.ProtoReflect.Descriptor instead.
func (*VoucherCode) Descriptor() ([]byte, []int) {
	return file_proto_payments_payments_proto_rawDescGZIP(), []int{2}
}

func (x *VoucherCode) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VoucherCode) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

// PaymentResponse contains information about the status of a payment.
type PaymentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status PaymentStatus `protobuf:"varint,1,opt,name=status,proto3,enum=payments.PaymentStatus" json:"status,omitempty"`
	// Types that are assignable to Provider:
	//
	//	*PaymentResponse_Empty
	//	*PaymentResponse_Stripe
	//	*PaymentResponse_Vipps
	Provider isPaymentResponse_Provider `protobuf_oneof:"provider"`
}

func (x *PaymentResponse) Reset() {
	*x = PaymentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_payments_payments_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentResponse) ProtoMessage() {}

func (x *PaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payments_payments_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentResponse.ProtoReflect.Descriptor instead.
func (*PaymentResponse) Descriptor() ([]byte, []int) {
	return file_proto_payments_payments_proto_rawDescGZIP(), []int{3}
}

func (x *PaymentResponse) GetStatus() PaymentStatus {
	if x != nil {
		return x.Status
	}
	return PaymentStatus_PAYMENT_STATUS_INVALID
}

func (m *PaymentResponse) GetProvider() isPaymentResponse_Provider {
	if m != nil {
		return m.Provider
	}
	return nil
}

func (x *PaymentResponse) GetEmpty() *utilspb.Empty {
	if x, ok := x.GetProvider().(*PaymentResponse_Empty); ok {
		return x.Empty
	}
	return nil
}

func (x *PaymentResponse) GetStripe() *StripePaymentResponse {
	if x, ok := x.GetProvider().(*PaymentResponse_Stripe); ok {
		return x.Stripe
	}
	return nil
}

func (x *PaymentResponse) GetVipps() *VippsPaymentResponse {
	if x, ok := x.GetProvider().(*PaymentResponse_Vipps); ok {
		return x.Vipps
	}
	return nil
}

type isPaymentResponse_Provider interface {
	isPaymentResponse_Provider()
}

type PaymentResponse_Empty struct {
	Empty *utilspb.Empty `protobuf:"bytes,2,opt,name=empty,proto3,oneof"`
}

type PaymentResponse_Stripe struct {
	Stripe *StripePaymentResponse `protobuf:"bytes,3,opt,name=stripe,proto3,oneof"`
}

type PaymentResponse_Vipps struct {
	Vipps *VippsPaymentResponse `protobuf:"bytes,4,opt,name=vipps,proto3,oneof"`
}

func (*PaymentResponse_Empty) isPaymentResponse_Provider() {}

func (*PaymentResponse_Stripe) isPaymentResponse_Provider() {}

func (*PaymentResponse_Vipps) isPaymentResponse_Provider() {}

// VoucherRequest contains information about required fields for redeeming a voucher code.
type VoucherRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Code is a 6-character alphanumerical (by en-US locale) code.
	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *VoucherRequest) Reset() {
	*x = VoucherRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_payments_payments_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VoucherRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoucherRequest) ProtoMessage() {}

func (x *VoucherRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payments_payments_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoucherRequest.ProtoReflect.Descriptor instead.
func (*VoucherRequest) Descriptor() ([]byte, []int) {
	return file_proto_payments_payments_proto_rawDescGZIP(), []int{4}
}

func (x *VoucherRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

// VoucherResponse contains information about a voucher.
type VoucherResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Code is a 6-character alphanumerical (by en-US locale) code.
	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	// The voucher code might be valid only for a specific country.
	Country string `protobuf:"bytes,2,opt,name=country,proto3" json:"country,omitempty"`
	// The voucher code might be valid only for a specific salon.
	SalonId string `protobuf:"bytes,3,opt,name=salon_id,json=salonId,proto3" json:"salon_id,omitempty"`
	// The voucher expires at a given date+time, given in milliseconds after Unix Epoch: https://en.wikipedia.org/wiki/Unix_time
	ExpiryDate int64 `protobuf:"varint,4,opt,name=expiry_date,json=expiryDate,proto3" json:"expiry_date,omitempty"`
}

func (x *VoucherResponse) Reset() {
	*x = VoucherResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_payments_payments_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VoucherResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoucherResponse) ProtoMessage() {}

func (x *VoucherResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payments_payments_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoucherResponse.ProtoReflect.Descriptor instead.
func (*VoucherResponse) Descriptor() ([]byte, []int) {
	return file_proto_payments_payments_proto_rawDescGZIP(), []int{5}
}

func (x *VoucherResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *VoucherResponse) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *VoucherResponse) GetSalonId() string {
	if x != nil {
		return x.SalonId
	}
	return ""
}

func (x *VoucherResponse) GetExpiryDate() int64 {
	if x != nil {
		return x.ExpiryDate
	}
	return 0
}

// CardRequest contains information about how a card setup should be done.
type CardRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Auth *authpb.Authentication `protobuf:"bytes,1,opt,name=auth,proto3" json:"auth,omitempty"`
	Card *Card                  `protobuf:"bytes,2,opt,name=card,proto3" json:"card,omitempty"`
	// Types that are assignable to Provider:
	//
	//	*CardRequest_Empty
	//	*CardRequest_Stripe
	Provider isCardRequest_Provider `protobuf_oneof:"provider"`
	// Setting error_on_not_found to true will cause the `ListCards` rpc to throw a NotFound error if no cards exists. This will be deprecated, aka default `true`, in a later version.
	ErrorOnNotFound bool `protobuf:"varint,17,opt,name=error_on_not_found,json=errorOnNotFound,proto3" json:"error_on_not_found,omitempty"`
}

func (x *CardRequest) Reset() {
	*x = CardRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_payments_payments_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardRequest) ProtoMessage() {}

func (x *CardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payments_payments_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardRequest.ProtoReflect.Descriptor instead.
func (*CardRequest) Descriptor() ([]byte, []int) {
	return file_proto_payments_payments_proto_rawDescGZIP(), []int{6}
}

func (x *CardRequest) GetAuth() *authpb.Authentication {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *CardRequest) GetCard() *Card {
	if x != nil {
		return x.Card
	}
	return nil
}

func (m *CardRequest) GetProvider() isCardRequest_Provider {
	if m != nil {
		return m.Provider
	}
	return nil
}

func (x *CardRequest) GetEmpty() *utilspb.Empty {
	if x, ok := x.GetProvider().(*CardRequest_Empty); ok {
		return x.Empty
	}
	return nil
}

func (x *CardRequest) GetStripe() *StripeCardRequest {
	if x, ok := x.GetProvider().(*CardRequest_Stripe); ok {
		return x.Stripe
	}
	return nil
}

func (x *CardRequest) GetErrorOnNotFound() bool {
	if x != nil {
		return x.ErrorOnNotFound
	}
	return false
}

type isCardRequest_Provider interface {
	isCardRequest_Provider()
}

type CardRequest_Empty struct {
	Empty *utilspb.Empty `protobuf:"bytes,3,opt,name=empty,proto3,oneof"`
}

type CardRequest_Stripe struct {
	Stripe *StripeCardRequest `protobuf:"bytes,4,opt,name=stripe,proto3,oneof"`
}

func (*CardRequest_Empty) isCardRequest_Provider() {}

func (*CardRequest_Stripe) isCardRequest_Provider() {}

// CardResponse contains information about the status of a card.
type CardResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Card   *Card      `protobuf:"bytes,1,opt,name=card,proto3" json:"card,omitempty"`
	Status CardStatus `protobuf:"varint,2,opt,name=status,proto3,enum=payments.CardStatus" json:"status,omitempty"`
	// Types that are assignable to Provider:
	//
	//	*CardResponse_Empty
	//	*CardResponse_Stripe
	Provider isCardResponse_Provider `protobuf_oneof:"provider"`
}

func (x *CardResponse) Reset() {
	*x = CardResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_payments_payments_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardResponse) ProtoMessage() {}

func (x *CardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payments_payments_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardResponse.ProtoReflect.Descriptor instead.
func (*CardResponse) Descriptor() ([]byte, []int) {
	return file_proto_payments_payments_proto_rawDescGZIP(), []int{7}
}

func (x *CardResponse) GetCard() *Card {
	if x != nil {
		return x.Card
	}
	return nil
}

func (x *CardResponse) GetStatus() CardStatus {
	if x != nil {
		return x.Status
	}
	return CardStatus_CARD_STATUS_INVALID
}

func (m *CardResponse) GetProvider() isCardResponse_Provider {
	if m != nil {
		return m.Provider
	}
	return nil
}

func (x *CardResponse) GetEmpty() *utilspb.Empty {
	if x, ok := x.GetProvider().(*CardResponse_Empty); ok {
		return x.Empty
	}
	return nil
}

func (x *CardResponse) GetStripe() *StripeCardResponse {
	if x, ok := x.GetProvider().(*CardResponse_Stripe); ok {
		return x.Stripe
	}
	return nil
}

type isCardResponse_Provider interface {
	isCardResponse_Provider()
}

type CardResponse_Empty struct {
	Empty *utilspb.Empty `protobuf:"bytes,3,opt,name=empty,proto3,oneof"`
}

type CardResponse_Stripe struct {
	Stripe *StripeCardResponse `protobuf:"bytes,4,opt,name=stripe,proto3,oneof"`
}

func (*CardResponse_Empty) isCardResponse_Provider() {}

func (*CardResponse_Stripe) isCardResponse_Provider() {}

// Card contains information about the card.
type Card struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LastFourDigits string `protobuf:"bytes,1,opt,name=last_four_digits,json=lastFourDigits,proto3" json:"last_four_digits,omitempty"`
	ExpiryYear     uint32 `protobuf:"varint,2,opt,name=expiry_year,json=expiryYear,proto3" json:"expiry_year,omitempty"`
	ExpiryMonth    uint32 `protobuf:"varint,3,opt,name=expiry_month,json=expiryMonth,proto3" json:"expiry_month,omitempty"`
	Brand          string `protobuf:"bytes,4,opt,name=brand,proto3" json:"brand,omitempty"`
}

func (x *Card) Reset() {
	*x = Card{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_payments_payments_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Card) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Card) ProtoMessage() {}

func (x *Card) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payments_payments_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Card.ProtoReflect.Descriptor instead.
func (*Card) Descriptor() ([]byte, []int) {
	return file_proto_payments_payments_proto_rawDescGZIP(), []int{8}
}

func (x *Card) GetLastFourDigits() string {
	if x != nil {
		return x.LastFourDigits
	}
	return ""
}

func (x *Card) GetExpiryYear() uint32 {
	if x != nil {
		return x.ExpiryYear
	}
	return 0
}

func (x *Card) GetExpiryMonth() uint32 {
	if x != nil {
		return x.ExpiryMonth
	}
	return 0
}

func (x *Card) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

var File_proto_payments_payments_proto protoreflect.FileDescriptor

var file_proto_payments_payments_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x73,
	0x2f, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x08, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x1a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x61, 0x75, 0x74, 0x68, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x2f, 0x6d, 0x6f,
	0x6e, 0x65, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x2f, 0x73, 0x74, 0x72, 0x69, 0x70, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x61,
	0x79, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x2f, 0x76, 0x69, 0x70, 0x70, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x75, 0x74, 0x69, 0x6c, 0x73, 0x2f,
	0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x82, 0x03, 0x0a, 0x0e,
	0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x24,
	0x0a, 0x05, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e,
	0x75, 0x74, 0x69, 0x6c, 0x73, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x48, 0x00, 0x52, 0x05, 0x65,
	0x6d, 0x70, 0x74, 0x79, 0x12, 0x38, 0x0a, 0x06, 0x73, 0x74, 0x72, 0x69, 0x70, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x2e,
	0x53, 0x74, 0x72, 0x69, 0x70, 0x65, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x06, 0x73, 0x74, 0x72, 0x69, 0x70, 0x65, 0x12, 0x35,
	0x0a, 0x05, 0x76, 0x69, 0x70, 0x70, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e,
	0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x56, 0x69, 0x70, 0x70, 0x73, 0x50, 0x61,
	0x79, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x05,
	0x76, 0x69, 0x70, 0x70, 0x73, 0x12, 0x32, 0x0a, 0x07, 0x76, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74,
	0x73, 0x2e, 0x56, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x52, 0x07, 0x76, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x12, 0x34, 0x0a, 0x08, 0x76, 0x6f, 0x75,
	0x63, 0x68, 0x65, 0x72, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x61,
	0x79, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x56, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x08, 0x76, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x73, 0x12,
	0x2e, 0x0a, 0x07, 0x63, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x43, 0x6f, 0x75, 0x70,
	0x6f, 0x6e, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x07, 0x63, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x73, 0x12,
	0x33, 0x0a, 0x0e, 0x65, 0x78, 0x70, 0x65, 0x63, 0x74, 0x65, 0x64, 0x5f, 0x70, 0x72, 0x69, 0x63,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x2e,
	0x50, 0x72, 0x69, 0x63, 0x65, 0x52, 0x0d, 0x65, 0x78, 0x70, 0x65, 0x63, 0x74, 0x65, 0x64, 0x50,
	0x72, 0x69, 0x63, 0x65, 0x42, 0x0a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72,
	0x22, 0x58, 0x0a, 0x0a, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x37, 0x0a, 0x0b, 0x56, 0x6f,
	0x75, 0x63, 0x68, 0x65, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x69, 0x64, 0x22, 0xe7, 0x01, 0x0a, 0x0f, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e,
	0x74, 0x73, 0x2e, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x24, 0x0a, 0x05, 0x65, 0x6d, 0x70, 0x74,
	0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x75, 0x74, 0x69, 0x6c, 0x73, 0x2e,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x48, 0x00, 0x52, 0x05, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x39,
	0x0a, 0x06, 0x73, 0x74, 0x72, 0x69, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f,
	0x2e, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x70, 0x65,
	0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48,
	0x00, 0x52, 0x06, 0x73, 0x74, 0x72, 0x69, 0x70, 0x65, 0x12, 0x36, 0x0a, 0x05, 0x76, 0x69, 0x70,
	0x70, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x70, 0x61, 0x79, 0x6d, 0x65,
	0x6e, 0x74, 0x73, 0x2e, 0x56, 0x69, 0x70, 0x70, 0x73, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x05, 0x76, 0x69, 0x70, 0x70,
	0x73, 0x42, 0x0a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x22, 0x24, 0x0a,
	0x0e, 0x56, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x22, 0x7b, 0x0a, 0x0f, 0x56, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x72, 0x79, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x61, 0x6c, 0x6f, 0x6e, 0x5f, 0x69, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x61, 0x6c, 0x6f, 0x6e, 0x49, 0x64, 0x12,
	0x1f, 0x0a, 0x0b, 0x65, 0x78, 0x70, 0x69, 0x72, 0x79, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x65, 0x78, 0x70, 0x69, 0x72, 0x79, 0x44, 0x61, 0x74, 0x65,
	0x22, 0xf1, 0x01, 0x0a, 0x0b, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x28, 0x0a, 0x04, 0x61, 0x75, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14,
	0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x04, 0x61, 0x75, 0x74, 0x68, 0x12, 0x22, 0x0a, 0x04, 0x63, 0x61,
	0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x61, 0x79, 0x6d, 0x65,
	0x6e, 0x74, 0x73, 0x2e, 0x43, 0x61, 0x72, 0x64, 0x52, 0x04, 0x63, 0x61, 0x72, 0x64, 0x12, 0x24,
	0x0a, 0x05, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e,
	0x75, 0x74, 0x69, 0x6c, 0x73, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x48, 0x00, 0x52, 0x05, 0x65,
	0x6d, 0x70, 0x74, 0x79, 0x12, 0x35, 0x0a, 0x06, 0x73, 0x74, 0x72, 0x69, 0x70, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x2e,
	0x53, 0x74, 0x72, 0x69, 0x70, 0x65, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x48, 0x00, 0x52, 0x06, 0x73, 0x74, 0x72, 0x69, 0x70, 0x65, 0x12, 0x2b, 0x0a, 0x12, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x5f, 0x6f, 0x6e, 0x5f, 0x6e, 0x6f, 0x74, 0x5f, 0x66, 0x6f, 0x75, 0x6e,
	0x64, 0x18, 0x11, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4f, 0x6e,
	0x4e, 0x6f, 0x74, 0x46, 0x6f, 0x75, 0x6e, 0x64, 0x42, 0x0a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x76,
	0x69, 0x64, 0x65, 0x72, 0x22, 0xca, 0x01, 0x0a, 0x0c, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x04, 0x63, 0x61, 0x72, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x43,
	0x61, 0x72, 0x64, 0x52, 0x04, 0x63, 0x61, 0x72, 0x64, 0x12, 0x2c, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x70, 0x61, 0x79, 0x6d,
	0x65, 0x6e, 0x74, 0x73, 0x2e, 0x43, 0x61, 0x72, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x24, 0x0a, 0x05, 0x65, 0x6d, 0x70, 0x74, 0x79,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x75, 0x74, 0x69, 0x6c, 0x73, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x48, 0x00, 0x52, 0x05, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x36, 0x0a,
	0x06, 0x73, 0x74, 0x72, 0x69, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e,
	0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x70, 0x65, 0x43,
	0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x06, 0x73,
	0x74, 0x72, 0x69, 0x70, 0x65, 0x42, 0x0a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65,
	0x72, 0x22, 0x8a, 0x01, 0x0a, 0x04, 0x43, 0x61, 0x72, 0x64, 0x12, 0x28, 0x0a, 0x10, 0x6c, 0x61,
	0x73, 0x74, 0x5f, 0x66, 0x6f, 0x75, 0x72, 0x5f, 0x64, 0x69, 0x67, 0x69, 0x74, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x6c, 0x61, 0x73, 0x74, 0x46, 0x6f, 0x75, 0x72, 0x44, 0x69,
	0x67, 0x69, 0x74, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x65, 0x78, 0x70, 0x69, 0x72, 0x79, 0x5f, 0x79,
	0x65, 0x61, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x65, 0x78, 0x70, 0x69, 0x72,
	0x79, 0x59, 0x65, 0x61, 0x72, 0x12, 0x21, 0x0a, 0x0c, 0x65, 0x78, 0x70, 0x69, 0x72, 0x79, 0x5f,
	0x6d, 0x6f, 0x6e, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x65, 0x78, 0x70,
	0x69, 0x72, 0x79, 0x4d, 0x6f, 0x6e, 0x74, 0x68, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x72, 0x61, 0x6e,
	0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x62, 0x72, 0x61, 0x6e, 0x64, 0x2a, 0xa0,
	0x01, 0x0a, 0x0d, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x1a, 0x0a, 0x16, 0x50, 0x41, 0x59, 0x4d, 0x45, 0x4e, 0x54, 0x5f, 0x53, 0x54, 0x41, 0x54,
	0x55, 0x53, 0x5f, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x10, 0x00, 0x12, 0x1a, 0x0a, 0x16,
	0x50, 0x41, 0x59, 0x4d, 0x45, 0x4e, 0x54, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x55,
	0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x01, 0x12, 0x1a, 0x0a, 0x16, 0x50, 0x41, 0x59, 0x4d,
	0x45, 0x4e, 0x54, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x53, 0x55, 0x43, 0x43, 0x45,
	0x53, 0x53, 0x10, 0x02, 0x12, 0x18, 0x0a, 0x14, 0x50, 0x41, 0x59, 0x4d, 0x45, 0x4e, 0x54, 0x5f,
	0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x03, 0x12, 0x21,
	0x0a, 0x1d, 0x50, 0x41, 0x59, 0x4d, 0x45, 0x4e, 0x54, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53,
	0x5f, 0x52, 0x45, 0x51, 0x55, 0x49, 0x52, 0x45, 0x5f, 0x41, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x10,
	0x04, 0x2a, 0x8e, 0x01, 0x0a, 0x0a, 0x43, 0x61, 0x72, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x17, 0x0a, 0x13, 0x43, 0x41, 0x52, 0x44, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f,
	0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x10, 0x00, 0x12, 0x17, 0x0a, 0x13, 0x43, 0x41, 0x52,
	0x44, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e,
	0x10, 0x01, 0x12, 0x17, 0x0a, 0x13, 0x43, 0x41, 0x52, 0x44, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55,
	0x53, 0x5f, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x02, 0x12, 0x15, 0x0a, 0x11, 0x43,
	0x41, 0x52, 0x44, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52,
	0x10, 0x03, 0x12, 0x1e, 0x0a, 0x1a, 0x43, 0x41, 0x52, 0x44, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55,
	0x53, 0x5f, 0x52, 0x45, 0x51, 0x55, 0x49, 0x52, 0x45, 0x5f, 0x41, 0x43, 0x54, 0x49, 0x4f, 0x4e,
	0x10, 0x04, 0x2a, 0xb4, 0x01, 0x0a, 0x0d, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x4d, 0x65,
	0x74, 0x68, 0x6f, 0x64, 0x12, 0x1a, 0x0a, 0x16, 0x50, 0x41, 0x59, 0x4d, 0x45, 0x4e, 0x54, 0x5f,
	0x4d, 0x45, 0x54, 0x48, 0x4f, 0x44, 0x5f, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x10, 0x00,
	0x12, 0x1a, 0x0a, 0x16, 0x50, 0x41, 0x59, 0x4d, 0x45, 0x4e, 0x54, 0x5f, 0x4d, 0x45, 0x54, 0x48,
	0x4f, 0x44, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x01, 0x12, 0x1a, 0x0a, 0x16,
	0x50, 0x41, 0x59, 0x4d, 0x45, 0x4e, 0x54, 0x5f, 0x4d, 0x45, 0x54, 0x48, 0x4f, 0x44, 0x5f, 0x56,
	0x4f, 0x55, 0x43, 0x48, 0x45, 0x52, 0x10, 0x02, 0x12, 0x19, 0x0a, 0x15, 0x50, 0x41, 0x59, 0x4d,
	0x45, 0x4e, 0x54, 0x5f, 0x4d, 0x45, 0x54, 0x48, 0x4f, 0x44, 0x5f, 0x53, 0x54, 0x52, 0x49, 0x50,
	0x45, 0x10, 0x03, 0x12, 0x18, 0x0a, 0x14, 0x50, 0x41, 0x59, 0x4d, 0x45, 0x4e, 0x54, 0x5f, 0x4d,
	0x45, 0x54, 0x48, 0x4f, 0x44, 0x5f, 0x56, 0x49, 0x50, 0x50, 0x53, 0x10, 0x04, 0x12, 0x1a, 0x0a,
	0x16, 0x50, 0x41, 0x59, 0x4d, 0x45, 0x4e, 0x54, 0x5f, 0x4d, 0x45, 0x54, 0x48, 0x4f, 0x44, 0x5f,
	0x57, 0x41, 0x4c, 0x4c, 0x4d, 0x4f, 0x42, 0x10, 0x05, 0x42, 0x3f, 0x5a, 0x3d, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x75, 0x74, 0x74, 0x65, 0x72, 0x73, 0x2d,
	0x64, 0x69, 0x67, 0x69, 0x74, 0x61, 0x6c, 0x2f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2d,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2f,
	0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_proto_payments_payments_proto_rawDescOnce sync.Once
	file_proto_payments_payments_proto_rawDescData = file_proto_payments_payments_proto_rawDesc
)

func file_proto_payments_payments_proto_rawDescGZIP() []byte {
	file_proto_payments_payments_proto_rawDescOnce.Do(func() {
		file_proto_payments_payments_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_payments_payments_proto_rawDescData)
	})
	return file_proto_payments_payments_proto_rawDescData
}

var file_proto_payments_payments_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_proto_payments_payments_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_payments_payments_proto_goTypes = []interface{}{
	(PaymentStatus)(0),            // 0: payments.PaymentStatus
	(CardStatus)(0),               // 1: payments.CardStatus
	(PaymentMethod)(0),            // 2: payments.PaymentMethod
	(*PaymentRequest)(nil),        // 3: payments.PaymentRequest
	(*CouponCode)(nil),            // 4: payments.CouponCode
	(*VoucherCode)(nil),           // 5: payments.VoucherCode
	(*PaymentResponse)(nil),       // 6: payments.PaymentResponse
	(*VoucherRequest)(nil),        // 7: payments.VoucherRequest
	(*VoucherResponse)(nil),       // 8: payments.VoucherResponse
	(*CardRequest)(nil),           // 9: payments.CardRequest
	(*CardResponse)(nil),          // 10: payments.CardResponse
	(*Card)(nil),                  // 11: payments.Card
	(*utilspb.Empty)(nil),         // 12: utils.Empty
	(*StripePaymentRequest)(nil),  // 13: payments.StripePaymentRequest
	(*VippsPaymentRequest)(nil),   // 14: payments.VippsPaymentRequest
	(*moneypb.Price)(nil),         // 15: money.Price
	(*StripePaymentResponse)(nil), // 16: payments.StripePaymentResponse
	(*VippsPaymentResponse)(nil),  // 17: payments.VippsPaymentResponse
	(*authpb.Authentication)(nil), // 18: auth.Authentication
	(*StripeCardRequest)(nil),     // 19: payments.StripeCardRequest
	(*StripeCardResponse)(nil),    // 20: payments.StripeCardResponse
}
var file_proto_payments_payments_proto_depIdxs = []int32{
	12, // 0: payments.PaymentRequest.empty:type_name -> utils.Empty
	13, // 1: payments.PaymentRequest.stripe:type_name -> payments.StripePaymentRequest
	14, // 2: payments.PaymentRequest.vipps:type_name -> payments.VippsPaymentRequest
	7,  // 3: payments.PaymentRequest.voucher:type_name -> payments.VoucherRequest
	7,  // 4: payments.PaymentRequest.vouchers:type_name -> payments.VoucherRequest
	4,  // 5: payments.PaymentRequest.coupons:type_name -> payments.CouponCode
	15, // 6: payments.PaymentRequest.expected_price:type_name -> money.Price
	0,  // 7: payments.PaymentResponse.status:type_name -> payments.PaymentStatus
	12, // 8: payments.PaymentResponse.empty:type_name -> utils.Empty
	16, // 9: payments.PaymentResponse.stripe:type_name -> payments.StripePaymentResponse
	17, // 10: payments.PaymentResponse.vipps:type_name -> payments.VippsPaymentResponse
	18, // 11: payments.CardRequest.auth:type_name -> auth.Authentication
	11, // 12: payments.CardRequest.card:type_name -> payments.Card
	12, // 13: payments.CardRequest.empty:type_name -> utils.Empty
	19, // 14: payments.CardRequest.stripe:type_name -> payments.StripeCardRequest
	11, // 15: payments.CardResponse.card:type_name -> payments.Card
	1,  // 16: payments.CardResponse.status:type_name -> payments.CardStatus
	12, // 17: payments.CardResponse.empty:type_name -> utils.Empty
	20, // 18: payments.CardResponse.stripe:type_name -> payments.StripeCardResponse
	19, // [19:19] is the sub-list for method output_type
	19, // [19:19] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_proto_payments_payments_proto_init() }
func file_proto_payments_payments_proto_init() {
	if File_proto_payments_payments_proto != nil {
		return
	}
	file_proto_payments_stripe_proto_init()
	file_proto_payments_vipps_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_proto_payments_payments_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaymentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_payments_payments_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CouponCode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_payments_payments_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VoucherCode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_payments_payments_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaymentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_payments_payments_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VoucherRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_payments_payments_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VoucherResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_payments_payments_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CardRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_payments_payments_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CardResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_payments_payments_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Card); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_payments_payments_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*PaymentRequest_Empty)(nil),
		(*PaymentRequest_Stripe)(nil),
		(*PaymentRequest_Vipps)(nil),
	}
	file_proto_payments_payments_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*PaymentResponse_Empty)(nil),
		(*PaymentResponse_Stripe)(nil),
		(*PaymentResponse_Vipps)(nil),
	}
	file_proto_payments_payments_proto_msgTypes[6].OneofWrappers = []interface{}{
		(*CardRequest_Empty)(nil),
		(*CardRequest_Stripe)(nil),
	}
	file_proto_payments_payments_proto_msgTypes[7].OneofWrappers = []interface{}{
		(*CardResponse_Empty)(nil),
		(*CardResponse_Stripe)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_payments_payments_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_payments_payments_proto_goTypes,
		DependencyIndexes: file_proto_payments_payments_proto_depIdxs,
		EnumInfos:         file_proto_payments_payments_proto_enumTypes,
		MessageInfos:      file_proto_payments_payments_proto_msgTypes,
	}.Build()
	File_proto_payments_payments_proto = out.File
	file_proto_payments_payments_proto_rawDesc = nil
	file_proto_payments_payments_proto_goTypes = nil
	file_proto_payments_payments_proto_depIdxs = nil
}
