// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.1
// source: proto/payments/vipps.proto

package paymentspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// VippsPaymentOperation indicates what the App thinks should be the next step of the flow.
type VippsPaymentOperation int32

const (
	VippsPaymentOperation_VIPPS_PAYMENT_OPERATION_INVALID  VippsPaymentOperation = 0
	VippsPaymentOperation_VIPPS_PAYMENT_OPERATION_INITIATE VippsPaymentOperation = 1
	VippsPaymentOperation_VIPPS_PAYMENT_OPERATION_CAPTURE  VippsPaymentOperation = 2
)

// Enum value maps for VippsPaymentOperation.
var (
	VippsPaymentOperation_name = map[int32]string{
		0: "VIPPS_PAYMENT_OPERATION_INVALID",
		1: "VIPPS_PAYMENT_OPERATION_INITIATE",
		2: "VIPPS_PAYMENT_OPERATION_CAPTURE",
	}
	VippsPaymentOperation_value = map[string]int32{
		"VIPPS_PAYMENT_OPERATION_INVALID":  0,
		"VIPPS_PAYMENT_OPERATION_INITIATE": 1,
		"VIPPS_PAYMENT_OPERATION_CAPTURE":  2,
	}
)

func (x VippsPaymentOperation) Enum() *VippsPaymentOperation {
	p := new(VippsPaymentOperation)
	*p = x
	return p
}

func (x VippsPaymentOperation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VippsPaymentOperation) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_payments_vipps_proto_enumTypes[0].Descriptor()
}

func (VippsPaymentOperation) Type() protoreflect.EnumType {
	return &file_proto_payments_vipps_proto_enumTypes[0]
}

func (x VippsPaymentOperation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VippsPaymentOperation.Descriptor instead.
func (VippsPaymentOperation) EnumDescriptor() ([]byte, []int) {
	return file_proto_payments_vipps_proto_rawDescGZIP(), []int{0}
}

// VippsPaymentRequest details the App to Gateway request for initiating and capturing Vipps payments.
type VippsPaymentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// operation should be Initiate for the first Purchase step, but Capture for the second purchase step.
	Operation VippsPaymentOperation `protobuf:"varint,1,opt,name=operation,proto3,enum=payments.VippsPaymentOperation" json:"operation,omitempty"`
	// order_id should be empty during the Initiate flow, but populated during the Capture flow.
	OrderId string `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	// fall_back url is the App provided deep link for returning the user to the Cutters App after completing the Vipps App flow.
	// Please see https://github.com/vippsas/vipps-ecom-api/blob/master/vipps-ecom-api.md#app-switching
	FallbackUrl string `protobuf:"bytes,3,opt,name=fallback_url,json=fallbackUrl,proto3" json:"fallback_url,omitempty"`
}

func (x *VippsPaymentRequest) Reset() {
	*x = VippsPaymentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_payments_vipps_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VippsPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VippsPaymentRequest) ProtoMessage() {}

func (x *VippsPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payments_vipps_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VippsPaymentRequest.ProtoReflect.Descriptor instead.
func (*VippsPaymentRequest) Descriptor() ([]byte, []int) {
	return file_proto_payments_vipps_proto_rawDescGZIP(), []int{0}
}

func (x *VippsPaymentRequest) GetOperation() VippsPaymentOperation {
	if x != nil {
		return x.Operation
	}
	return VippsPaymentOperation_VIPPS_PAYMENT_OPERATION_INVALID
}

func (x *VippsPaymentRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *VippsPaymentRequest) GetFallbackUrl() string {
	if x != nil {
		return x.FallbackUrl
	}
	return ""
}

// VippsPaymentResponse details the Gateway to App response for the current payment along with the Vipps deep link.
type VippsPaymentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// order_id should hold the orderID generated by the gateway.
	OrderId string `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	// deep_link should hold the Vipps provided deep link to the Vipps app.
	DeepLink string `protobuf:"bytes,2,opt,name=deep_link,json=deepLink,proto3" json:"deep_link,omitempty"`
}

func (x *VippsPaymentResponse) Reset() {
	*x = VippsPaymentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_payments_vipps_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VippsPaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VippsPaymentResponse) ProtoMessage() {}

func (x *VippsPaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payments_vipps_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VippsPaymentResponse.ProtoReflect.Descriptor instead.
func (*VippsPaymentResponse) Descriptor() ([]byte, []int) {
	return file_proto_payments_vipps_proto_rawDescGZIP(), []int{1}
}

func (x *VippsPaymentResponse) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *VippsPaymentResponse) GetDeepLink() string {
	if x != nil {
		return x.DeepLink
	}
	return ""
}

var File_proto_payments_vipps_proto protoreflect.FileDescriptor

var file_proto_payments_vipps_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x73,
	0x2f, 0x76, 0x69, 0x70, 0x70, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x61,
	0x79, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x92, 0x01, 0x0a, 0x13, 0x56, 0x69, 0x70, 0x70, 0x73,
	0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3d,
	0x0a, 0x09, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x1f, 0x2e, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x56, 0x69, 0x70,
	0x70, 0x73, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x09, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x19, 0x0a,
	0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x66, 0x61, 0x6c, 0x6c,
	0x62, 0x61, 0x63, 0x6b, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x66, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x55, 0x72, 0x6c, 0x22, 0x4e, 0x0a, 0x14, 0x56,
	0x69, 0x70, 0x70, 0x73, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1b,
	0x0a, 0x09, 0x64, 0x65, 0x65, 0x70, 0x5f, 0x6c, 0x69, 0x6e, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x64, 0x65, 0x65, 0x70, 0x4c, 0x69, 0x6e, 0x6b, 0x2a, 0x87, 0x01, 0x0a, 0x15,
	0x56, 0x69, 0x70, 0x70, 0x73, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x4f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x23, 0x0a, 0x1f, 0x56, 0x49, 0x50, 0x50, 0x53, 0x5f, 0x50,
	0x41, 0x59, 0x4d, 0x45, 0x4e, 0x54, 0x5f, 0x4f, 0x50, 0x45, 0x52, 0x41, 0x54, 0x49, 0x4f, 0x4e,
	0x5f, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x10, 0x00, 0x12, 0x24, 0x0a, 0x20, 0x56, 0x49,
	0x50, 0x50, 0x53, 0x5f, 0x50, 0x41, 0x59, 0x4d, 0x45, 0x4e, 0x54, 0x5f, 0x4f, 0x50, 0x45, 0x52,
	0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x49, 0x4e, 0x49, 0x54, 0x49, 0x41, 0x54, 0x45, 0x10, 0x01,
	0x12, 0x23, 0x0a, 0x1f, 0x56, 0x49, 0x50, 0x50, 0x53, 0x5f, 0x50, 0x41, 0x59, 0x4d, 0x45, 0x4e,
	0x54, 0x5f, 0x4f, 0x50, 0x45, 0x52, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x43, 0x41, 0x50, 0x54,
	0x55, 0x52, 0x45, 0x10, 0x02, 0x42, 0x3f, 0x5a, 0x3d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x75, 0x74, 0x74, 0x65, 0x72, 0x73, 0x2d, 0x64, 0x69, 0x67, 0x69,
	0x74, 0x61, 0x6c, 0x2f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2d, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2f, 0x70, 0x61, 0x79, 0x6d,
	0x65, 0x6e, 0x74, 0x73, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_payments_vipps_proto_rawDescOnce sync.Once
	file_proto_payments_vipps_proto_rawDescData = file_proto_payments_vipps_proto_rawDesc
)

func file_proto_payments_vipps_proto_rawDescGZIP() []byte {
	file_proto_payments_vipps_proto_rawDescOnce.Do(func() {
		file_proto_payments_vipps_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_payments_vipps_proto_rawDescData)
	})
	return file_proto_payments_vipps_proto_rawDescData
}

var file_proto_payments_vipps_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_payments_vipps_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_payments_vipps_proto_goTypes = []interface{}{
	(VippsPaymentOperation)(0),   // 0: payments.VippsPaymentOperation
	(*VippsPaymentRequest)(nil),  // 1: payments.VippsPaymentRequest
	(*VippsPaymentResponse)(nil), // 2: payments.VippsPaymentResponse
}
var file_proto_payments_vipps_proto_depIdxs = []int32{
	0, // 0: payments.VippsPaymentRequest.operation:type_name -> payments.VippsPaymentOperation
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_payments_vipps_proto_init() }
func file_proto_payments_vipps_proto_init() {
	if File_proto_payments_vipps_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_payments_vipps_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VippsPaymentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_payments_vipps_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VippsPaymentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_payments_vipps_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_payments_vipps_proto_goTypes,
		DependencyIndexes: file_proto_payments_vipps_proto_depIdxs,
		EnumInfos:         file_proto_payments_vipps_proto_enumTypes,
		MessageInfos:      file_proto_payments_vipps_proto_msgTypes,
	}.Build()
	File_proto_payments_vipps_proto = out.File
	file_proto_payments_vipps_proto_rawDesc = nil
	file_proto_payments_vipps_proto_goTypes = nil
	file_proto_payments_vipps_proto_depIdxs = nil
}
