// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: proto/user/user_api.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// Gender contains all genders, while allowing "OTHER" as a catch-all for those that don't fit into a non-binary gender-world.
public enum User_Gender: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case invalid // = 0
  case other // = 1
  case male // = 2
  case female // = 3
  case UNRECOGNIZED(Int)

  public init() {
    self = .invalid
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .invalid
    case 1: self = .other
    case 2: self = .male
    case 3: self = .female
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .invalid: return 0
    case .other: return 1
    case .male: return 2
    case .female: return 3
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [User_Gender] = [
    .invalid,
    .other,
    .male,
    .female,
  ]

}

public struct User_UserRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var auth: Auth_Authentication {
    get {return _auth ?? Auth_Authentication()}
    set {_auth = newValue}
  }
  /// Returns true if `auth` has been explicitly set.
  public var hasAuth: Bool {return self._auth != nil}
  /// Clears the value of `auth`. Subsequent reads from it will return its default value.
  public mutating func clearAuth() {self._auth = nil}

  public var user: User_User {
    get {return _user ?? User_User()}
    set {_user = newValue}
  }
  /// Returns true if `user` has been explicitly set.
  public var hasUser: Bool {return self._user != nil}
  /// Clears the value of `user`. Subsequent reads from it will return its default value.
  public mutating func clearUser() {self._user = nil}

  /// Setting error_on_not_found to true will cause the `GetUser` rpc to throw a NotFound error if the customer does not exist. This will be deprecated, aka default `true`, in a later version.
  ///
  /// NOTE: This field was marked as deprecated in the .proto file.
  public var errorOnNotFound: Bool = false

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _auth: Auth_Authentication? = nil
  fileprivate var _user: User_User? = nil
}

public struct User_UserResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var user: User_User {
    get {return _user ?? User_User()}
    set {_user = newValue}
  }
  /// Returns true if `user` has been explicitly set.
  public var hasUser: Bool {return self._user != nil}
  /// Clears the value of `user`. Subsequent reads from it will return its default value.
  public mutating func clearUser() {self._user = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _user: User_User? = nil
}

public struct User_UpdateUserNotificationRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var auth: Auth_Authentication {
    get {return _auth ?? Auth_Authentication()}
    set {_auth = newValue}
  }
  /// Returns true if `auth` has been explicitly set.
  public var hasAuth: Bool {return self._auth != nil}
  /// Clears the value of `auth`. Subsequent reads from it will return its default value.
  public mutating func clearAuth() {self._auth = nil}

  public var notification: Notifications_Notification {
    get {return _notification ?? Notifications_Notification()}
    set {_notification = newValue}
  }
  /// Returns true if `notification` has been explicitly set.
  public var hasNotification: Bool {return self._notification != nil}
  /// Clears the value of `notification`. Subsequent reads from it will return its default value.
  public mutating func clearNotification() {self._notification = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _auth: Auth_Authentication? = nil
  fileprivate var _notification: Notifications_Notification? = nil
}

public struct User_UpdateUserNotificationResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// User contains all the personal details we know about the user.
public struct User_User: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Name = First-name. Required. Will be displayed on the monitors in the salon when purchasing a cut.
  public var name: String = String()

  /// Email. Required. Receipts will be sent to this email.
  public var email: String = String()

  public var localePreference: String = String()

  /// Phone number contains the country-code and phone-number, prefixed with "+", e.g.: "+4712345678". Will be ignored if supplied in a UserRequest.
  public var phoneNumber: String = String()

  /// Notification contains information about the Firebase Cloud Messaging token to send notifications to a user.
  public var notification: Notifications_Notification {
    get {return _notification ?? Notifications_Notification()}
    set {_notification = newValue}
  }
  /// Returns true if `notification` has been explicitly set.
  public var hasNotification: Bool {return self._notification != nil}
  /// Clears the value of `notification`. Subsequent reads from it will return its default value.
  public mutating func clearNotification() {self._notification = nil}

  /// The birthday is given in seconds after Unix Epoch: https://en.wikipedia.org/wiki/Unix_time
  public var birthday: Utils_Timestamp {
    get {return _birthday ?? Utils_Timestamp()}
    set {_birthday = newValue}
  }
  /// Returns true if `birthday` has been explicitly set.
  public var hasBirthday: Bool {return self._birthday != nil}
  /// Clears the value of `birthday`. Subsequent reads from it will return its default value.
  public mutating func clearBirthday() {self._birthday = nil}

  public var gender: User_Gender = .invalid

  public var address: String = String()

  public var postalCode: String = String()

  public var postalPlace: String = String()

  public var allowMarketing: Bool = false

  /// Last name is optional.
  public var lastName: String = String()

  /// Should be exclusive with birthday, with the full date taking priority: if birthdate set, birth_year should be ignored.
  public var birthYear: Int32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _notification: Notifications_Notification? = nil
  fileprivate var _birthday: Utils_Timestamp? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "user"

extension User_Gender: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "GENDER_INVALID"),
    1: .same(proto: "GENDER_OTHER"),
    2: .same(proto: "GENDER_MALE"),
    3: .same(proto: "GENDER_FEMALE"),
  ]
}

extension User_UserRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".UserRequest"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "auth"),
    2: .same(proto: "user"),
    17: .standard(proto: "error_on_not_found"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._auth) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._user) }()
      case 17: try { try decoder.decodeSingularBoolField(value: &self.errorOnNotFound) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._auth {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._user {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    if self.errorOnNotFound != false {
      try visitor.visitSingularBoolField(value: self.errorOnNotFound, fieldNumber: 17)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: User_UserRequest, rhs: User_UserRequest) -> Bool {
    if lhs._auth != rhs._auth {return false}
    if lhs._user != rhs._user {return false}
    if lhs.errorOnNotFound != rhs.errorOnNotFound {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension User_UserResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".UserResponse"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "user"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._user) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._user {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: User_UserResponse, rhs: User_UserResponse) -> Bool {
    if lhs._user != rhs._user {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension User_UpdateUserNotificationRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".UpdateUserNotificationRequest"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "auth"),
    2: .same(proto: "notification"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._auth) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._notification) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._auth {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._notification {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: User_UpdateUserNotificationRequest, rhs: User_UpdateUserNotificationRequest) -> Bool {
    if lhs._auth != rhs._auth {return false}
    if lhs._notification != rhs._notification {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension User_UpdateUserNotificationResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".UpdateUserNotificationResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: User_UpdateUserNotificationResponse, rhs: User_UpdateUserNotificationResponse) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension User_User: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".User"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "name"),
    2: .same(proto: "email"),
    3: .standard(proto: "locale_preference"),
    4: .standard(proto: "phone_number"),
    5: .same(proto: "notification"),
    6: .same(proto: "birthday"),
    7: .same(proto: "gender"),
    8: .same(proto: "address"),
    9: .standard(proto: "postal_code"),
    10: .standard(proto: "postal_place"),
    11: .standard(proto: "allow_marketing"),
    12: .standard(proto: "last_name"),
    13: .standard(proto: "birth_year"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.email) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.localePreference) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.phoneNumber) }()
      case 5: try { try decoder.decodeSingularMessageField(value: &self._notification) }()
      case 6: try { try decoder.decodeSingularMessageField(value: &self._birthday) }()
      case 7: try { try decoder.decodeSingularEnumField(value: &self.gender) }()
      case 8: try { try decoder.decodeSingularStringField(value: &self.address) }()
      case 9: try { try decoder.decodeSingularStringField(value: &self.postalCode) }()
      case 10: try { try decoder.decodeSingularStringField(value: &self.postalPlace) }()
      case 11: try { try decoder.decodeSingularBoolField(value: &self.allowMarketing) }()
      case 12: try { try decoder.decodeSingularStringField(value: &self.lastName) }()
      case 13: try { try decoder.decodeSingularInt32Field(value: &self.birthYear) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    if !self.email.isEmpty {
      try visitor.visitSingularStringField(value: self.email, fieldNumber: 2)
    }
    if !self.localePreference.isEmpty {
      try visitor.visitSingularStringField(value: self.localePreference, fieldNumber: 3)
    }
    if !self.phoneNumber.isEmpty {
      try visitor.visitSingularStringField(value: self.phoneNumber, fieldNumber: 4)
    }
    try { if let v = self._notification {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    } }()
    try { if let v = self._birthday {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
    } }()
    if self.gender != .invalid {
      try visitor.visitSingularEnumField(value: self.gender, fieldNumber: 7)
    }
    if !self.address.isEmpty {
      try visitor.visitSingularStringField(value: self.address, fieldNumber: 8)
    }
    if !self.postalCode.isEmpty {
      try visitor.visitSingularStringField(value: self.postalCode, fieldNumber: 9)
    }
    if !self.postalPlace.isEmpty {
      try visitor.visitSingularStringField(value: self.postalPlace, fieldNumber: 10)
    }
    if self.allowMarketing != false {
      try visitor.visitSingularBoolField(value: self.allowMarketing, fieldNumber: 11)
    }
    if !self.lastName.isEmpty {
      try visitor.visitSingularStringField(value: self.lastName, fieldNumber: 12)
    }
    if self.birthYear != 0 {
      try visitor.visitSingularInt32Field(value: self.birthYear, fieldNumber: 13)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: User_User, rhs: User_User) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs.email != rhs.email {return false}
    if lhs.localePreference != rhs.localePreference {return false}
    if lhs.phoneNumber != rhs.phoneNumber {return false}
    if lhs._notification != rhs._notification {return false}
    if lhs._birthday != rhs._birthday {return false}
    if lhs.gender != rhs.gender {return false}
    if lhs.address != rhs.address {return false}
    if lhs.postalCode != rhs.postalCode {return false}
    if lhs.postalPlace != rhs.postalPlace {return false}
    if lhs.allowMarketing != rhs.allowMarketing {return false}
    if lhs.lastName != rhs.lastName {return false}
    if lhs.birthYear != rhs.birthYear {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
