// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/payments/card_api.proto

// Protobuf Java Version: 3.25.1
package payments;

public final class CardApi {
  private CardApi() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035proto/payments/card_api.proto\022\010payment" +
      "s\032\035proto/payments/payments.proto2\376\001\n\007Car" +
      "dAPI\022;\n\nCreateCard\022\025.payments.CardReques" +
      "t\032\026.payments.CardResponse\022;\n\nUpdateCard\022" +
      "\025.payments.CardRequest\032\026.payments.CardRe" +
      "sponse\022;\n\nDeleteCard\022\025.payments.CardRequ" +
      "est\032\026.payments.CardResponse\022<\n\tListCards" +
      "\022\025.payments.CardRequest\032\026.payments.CardR" +
      "esponse0\001B?Z=github.com/cutters-digital/" +
      "gateway-protobuf/golang/paymentspbb\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          payments.Payments.getDescriptor(),
        });
    payments.Payments.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
